# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
install: R -q -e "install.packages('enc'); print(c('Lib paths after installation are:',.libPaths()))"
before_script: Rscript "r-profile"
script: Rscript "show-lib-paths"